### ISSUE TITLE
Windows Defender Alert (probably false-positive)

### ISSUE THREAD

**Issue by antonio-gil** [lordfiSh/win10privacyfix#1]
Hi, good evening.

I've downloaded the last release from this site, and after a couple of minutes Windows Defender had thrown an alert, which can be viewed below:

![2015-09-08_20h41_12](https://cloud.githubusercontent.com/assets/9835489/9751426/49e43266-566a-11e5-9ef9-bf6cd7c66075.png)

I know that it could be Windows being a little paranoid, but I think that it was worth to comment/report. By the way, both alerts are from the same file. I was re-downloading the app when Windows Defender alerted me.

By the way, my system is a Windows 10 Pro x64, build 10240.

Best regards!

**Comment by lordfiSh** [comment]
There are not Viruses inside, its a false-positive. Autoit complied exe file are often reported.
I tought about re-writing this tool in C#, but since I got no feedback I decided to drop this project.
